//! Auto-generated by codegen v0.1.0
//! IR hash: 9343293228317031
//! Source-facing translations are created and verified only through `make advance`.

#![allow(non_snake_case, dead_code, unused_variables, non_camel_case_types)]

pub mod types;

pub mod cc;
pub mod engine;
pub mod render;
pub mod ui;
pub mod user;
pub mod xml;

